goBuild:
  stage: build
  image: weavelab/weavebuilder:v1.0.0
  script:
    - /usr/local/bin/gobuilder
  artifacts:
    untracked: true
cdTools:
  stage: deploy
  image: weavelab/cd-tools:v1.0.0
  script:
    - /bin/cd-tools
  dependencies:
    - goBuild